# Generated by Django 2.2 on 2019-04-21 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what_todo', models.CharField(max_length=100, verbose_name='Event')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date_time', models.DateTimeField(verbose_name='When should i remind you ? ')),
                ('state_user', models.BooleanField(default=False, verbose_name='Done ?')),
                ('state_db', models.BooleanField(default=False)),
                ('email_sent', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
